create table "public"."ggggg" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."ggggg" enable row level security;

CREATE UNIQUE INDEX ggggg_pkey ON public.ggggg USING btree (id);

alter table "public"."ggggg" add constraint "ggggg_pkey" PRIMARY KEY using index "ggggg_pkey";

grant delete on table "public"."ggggg" to "anon";

grant insert on table "public"."ggggg" to "anon";

grant references on table "public"."ggggg" to "anon";

grant select on table "public"."ggggg" to "anon";

grant trigger on table "public"."ggggg" to "anon";

grant truncate on table "public"."ggggg" to "anon";

grant update on table "public"."ggggg" to "anon";

grant delete on table "public"."ggggg" to "authenticated";

grant insert on table "public"."ggggg" to "authenticated";

grant references on table "public"."ggggg" to "authenticated";

grant select on table "public"."ggggg" to "authenticated";

grant trigger on table "public"."ggggg" to "authenticated";

grant truncate on table "public"."ggggg" to "authenticated";

grant update on table "public"."ggggg" to "authenticated";

grant delete on table "public"."ggggg" to "service_role";

grant insert on table "public"."ggggg" to "service_role";

grant references on table "public"."ggggg" to "service_role";

grant select on table "public"."ggggg" to "service_role";

grant trigger on table "public"."ggggg" to "service_role";

grant truncate on table "public"."ggggg" to "service_role";

grant update on table "public"."ggggg" to "service_role";


