// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgyfgxfwlymsrnpfdilx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpneWZneGZ3bHltc3JucGZkaWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4Njc2OTIsImV4cCI6MjA1NTQ0MzY5Mn0.zNsq34zgC6DurzokmwUdHUupZRMRPOFYJ7zFazbz1gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);