name: Deploy Dev to Prod
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DEV_PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
      PROD_PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install expect -y

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.20.5

      - name: Login to Supabase CLI
        run: |
          supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link Dev Project
        run: |
          expect << EOF
          spawn supabase link --project-ref $DEV_PROJECT_ID
          expect "Enter your database password (or leave blank to skip):"
          send "$DEV_DB_PASSWORD\r"
          interact
          EOF


      - name: Pull schema from dev branch
        run: |
          supabase db pull --db-url "postgresql://postgres.pmqmkzpriikzvvzlkmgk:${{ secrets.DEV_DB_PASSWORD }}@aws-0-us-east-1.pooler.supabase.com:5432/postgres"


      - name: Commit migrations
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add supabase/migrations/
          git commit -m "Auto-commit schema changes from dev" || echo "No changes to commit"
          git push origin dev


      - name: Link Prod Project
        run: |
          supabase db push --db-url "postgresql://postgres.jgyfgxfwlymsrnpfdilx:${{ secrets.PROD_DB_PASSWORD }}@aws-0-us-east-1.pooler.supabase.com:5432/postgres"

          
