name: Deploy Dev to Prod
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEV_PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
      PROD_PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
      DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.20.5

      - name: Login to Supabase CLI
        run: |
          supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link Dev Project
        run: |
          echo "$DEV_DB_PASSWORD" | supabase link --project-ref $DEV_PROJECT_ID

      - name: Pull schema from dev branch
        run: |
          supabase db pull  # Generates migration scripts from Studio changes

      - name: Commit migrations
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add supabase/migrations/
          git commit -m "Auto-commit schema changes from dev" || echo "No changes to commit"
          git push origin dev

      - name: Link Prod Project
        run: |
          echo "$PROD_DB_PASSWORD" | supabase link --project-ref $PROD_PROJECT_ID

      - name: Deploy to production
        run: |
          supabase db push  # Apply all migrations to prod
